### PR TITLE
Update android core version to fix some compile issues.

### PR DESCRIPTION
**Pull request by ernestmc**
This PR updates the `android_15` version to 0.3+ which solves the compile errors reported in #51 and #55.

### CODE REVIEW

**Comment by ernestmc** [comment]
I signed it!

**Comment by adamantivm** [comment]
@ernestmc while you're doing this, would you mind updating all dependencies in all projects to make them kinetic compatible? That will probably get us the closest to a more consistent, working version for kinetic.

**Comment by ernestmc** [comment]
@adamantivm I've updated the dependencies to the latest versions.

**Comment by adamantivm** [comment]
thank you, @ernestmc! I think it's good to go, as soon as you can settle your argument with the @googlebot

**Pull request merged**
