### PR TITLE
Changed robot frame base_link to base_footprint

### PR DESCRIPTION
**Pull request by FlorGrosso**
Changed robot frame from base_link to base_footprint, in file strings.xml.

### CODE REVIEW

**Comment by FlorGrosso** [comment]
I signed it!

**Comment by adamantivm** [comment]
@FlorGrosso thank you! But could you please remove the gradle wrapper files, and only submit the change to the resources file? Thanks!

**Comment by FlorGrosso** [comment]
@adamantivm comment addressed, ready for another pass.

**Comment by adamantivm** [comment]
Thanks @FlorGrosso !

**Pull request merged**
